### PR TITLE
Whole lotta fixes

### PR DESCRIPTION
**Pull request by wile-e1**
All printheads have had a small modeling artifact removed from them
All printhead CAD has been updated and re-exported
V6 CAD has had weird broken mirror feature repaired
All printheads have been harmonized to have same PTFE tube port diameter
Switchwire carriage CAD has been bug-zapped
Switchwire carriage CAD has had mount block added to it

### CODE REVIEW

**Comment by nemgrea** [comment]
https://github.com/VoronDesign/Voron-Stealthburner/issues/34

**Comment by BHoggs** [comment]
Is this going to get merged soon?

**Comment by nemgrea** [comment]
As soon as the issue 34 file name is corrected then yes

**Comment by wile-e1** [comment]
> Is this going to get merged soon?

Life has been a little bananas lately.  I haven't had much time for design work, but hoping things are going to calm down soon.


@nemgrea    Revised CAD assembly updated with M3x12

**Pull request merged**
