### PR TITLE
Thicken CW2 latch

### PR DESCRIPTION
**Pull request by kyleisah**
We've seen several reports of CW2 latches failing. The part is pretty thin, so I have thickened it to force a bit more infill rather than gap fill in the "neck" of the latch.

### CODE REVIEW

**Comment by kyleisah** [comment]
Well, I wanted to split them into 2 separate PR's but I don't know how to do that. This PR will also upload CAD and STLs for the Rapido mount with slight feature adjustments that will allow clearance when using Rapido with Voron Tap.

**Comment by kyleisah** [comment]
> Well, I wanted to split them into 2 separate PR's but I don't know how to do that. This PR will also upload CAD and STLs for the Rapido mount with slight feature adjustments that will allow clearance when using Rapido with Voron Tap.

Fixed!

**Comment by raymondh2** [comment]
@wile-e1

**Comment by tinymachines3d** [comment]
Just worked on this today! Still not thick enough for heavy hands. 

https://github.com/VoronDesign/Voron-Stealthburner/compare/main...tinymachines3d:Voron-Stealthburner:main

**Pull request closed without merging**
