### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by nemgrea**
missing belt clamp stl for SW x carriage

### CODE REVIEW

**Comment by jtdowney** [comment]
The deearing tool looks like it is missing the second part. This is just the handle.

**Comment by timmit99** [comment]
Also, @nemgrea  i think a rename for the DeEaring tool would be more clear about its purpose. `Stealthburner5015_Cutting_Tool.stl` would be more direct and pointed at its use.

**Comment by nemgrea** [comment]
> The deearing tool looks like it is missing the second part. This is just the handle.

fixed

**Comment by nemgrea** [comment]
> Also, @nemgrea i think a rename for the DeEaring tool would be more clear about its purpose. `Stealthburner5015_Cutting_Tool.stl` would be more direct and pointed at its use.

fixed

**Review by KiloQubit — APPROVED** [review]

**Pull request merged**
