### PR TITLE
Changed M3 Threaded inserts to be in spec from Sourcing Guide Spec sheets.

### PR DESCRIPTION
**Pull request by evader**
Changed the M3 inserts to be in spec with the sourcing guide spec sheets. Could not upload step file as above 25meg limit. Please delete if this isnt correct way to contribute.

### CODE REVIEW

**Comment by hartk1213** [comment]
@evader 

>  Changed the M3 inserts to be in spec with the sourcing guide spec sheets. Could not upload step file as above 25meg limit. Please delete if this isnt correct way to contribute.


just curious what you changed looking at your CAD file you uploaded compared to latest CW2 that is currently in the repo 
I changed the color to differentiate between the two because I cant see any changes 

brass colored is from your file, white is from latest cad assembly 

image

**Comment by BerzerkaDurk** [comment]
Looks like the length of the lower cylindrical portion is slightly shorter on the brass colored part. ha ha

**Comment by hartk1213** [comment]
> Looks like the length of the lower cylindrical portion is slightly shorter on the brass colored part. ha ha

yeah besides that there is no other change, 

the overall size of the threaded insert is the same 

i dont think this change is really needed 

as now they wouldnt match the rest of the printer assembly cad files, 

going to close this PR

**Comment by evader** [comment]
No problems at all. Just noticed it when i was doing some stuff so I thought id let you guys know. Thanks Hartk. Big fan here.

Cheers

**Pull request closed without merging**
